### PR TITLE
mp3 files render in an audio tag that has controls

### PR DESCRIPTION
**Pull request by maml**
Renders an audio player with controls instead of an empty preview image for mp3 files.

### CODE REVIEW

**Comment by orlando** [comment]
This looks good @maml, can you rebase the commits to get this merged please?

**Comment by maml** [comment]
Awesome - will do, thx!

**Comment by maml** [comment]
@orlando I rebased my commits down to one and then pulled the latest from master and it looks like everything was up-to-date. Please let me know if you need anything else.

**Comment by orlando** [comment]
@maml thanks

**Pull request merged**
